global:
  scrape_interval: 5s   # scrape every 15 seconds
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"   # matches service name in docker-compose

rule_files:
  - /etc/prometheus/rules.yml   # load your alert rules

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]   # assumes node_exporter is running
        labels:
          instance: "node2"
